language: python
python:
  - "3.6.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - cp config.example.py config.py
  - python -m unittest